apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-ui-deployment
spec: 
  selector:
    matchLabels:
      app: demo-ui
  replicas: 3 
  template:
    metadata:
      labels:
        app: demo-ui
    spec:
      containers:
      - name: demo-ui-container
        image: beachcoder/external:6
        env: 
        - name: SERVER
          value: "http://demo-service:8082"
        - name: SERVICE_PORT
          value: "8080"
        ports:
        - containerPort: 8080
            
        